### ISSUE TITLE
增加一个tip类型

### ISSUE THREAD

**Issue by showurl** [cherish-chat/xxim-sdk-flutter#12]
用途：灰色小字提示, 比如：xxx加入群聊、xxx撤回了一条消息...
<img width="532" alt="image" src="https://user-images.githubusercontent.com/49354784/213467671-4aa1101c-9c8a-4ff2-bf6a-7bc97f23be7f.png">

**Comment by DizzyDuan** [comment]
不建议撤回使用tip，（xxx撤回了一条消息）使用ContentType.revoke、RevokeContent.text。

**Comment by DizzyDuan** [comment]
LGTM
